name: Auto Build Cydia Repo
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dpkg-dev
        run: sudo apt update && sudo apt install dpkg-dev -y

      - name: Generate index
        run: |
          dpkg-scanpackages debs /dev/null > Packages
          gzip -k -f Packages

      - name: Commit index files
        run: |
          git config --global user.name "RepoAutoBot"
          git config --global user.email "bot@github.com"
          git add Packages Packages.gz
          if git diff --cached --quiet; then
            echo "No index changes, skip push"
            exit 0
          fi
          git commit -m "Auto update Packages index"
          git push
